---
title: "Webscraping"
author: "Dominik Peter"
date: "22 12 2016"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(pander)
knitr::opts_chunk$set(echo = TRUE)
```

>
>

## Webscraping

### Extrahieren der Tabelle aus Wikipedia
```{r getdata}
url <- 'https://de.wikipedia.org/wiki/Bern'

df <- url %>%
  read_html(.) %>%
  html_table(fill = TRUE, header = TRUE) %>% 
  .[[6]] %>% 
  na.omit(.) %>% 
  as.data.table(.) %>% 
  .[, 1:13, with = FALSE]

setnames(df, 1, "typ")
```

### Transformation und Bereinigung der Daten
```{r bereinigen, fig.align='center'}
# convert value to numeric and eliminate NA columns
to_numeric <- function(x) {
  x <- str_replace_all(x, ",", "\\.")
  as.numeric(x)
}
months <- colnames(df)[-1]
# apply function
df[, months] <- lapply(df[, months, with = FALSE], to_numeric)

tidy_df <- df[1:3] %>%
  melt(id.vars = "typ", variable.name = "Monat") %>% 
  dcast(Monat ~ typ)

col_names <- colnames(tidy_df)
setnames(tidy_df, col_names, c(col_names[1], c("Max", "Min", "Mittelwert")))

pander(tidy_df, style = "rmarkdown")
```

### Grafische Darstellung

Just for Fun

```{r plotting, fig.align='center', fig.width=10, fig.height=6, error=FALSE, comment=FALSE}
mean_temp <- mean(tidy_df$Mittelwert)
min <- scales::comma(tidy_df$Min)
max <- scales::comma(tidy_df$Max)

tidy_df  %>% 
  ggplot(aes(x = Monat, y = Mittelwert)) +
  geom_point(size = 1.5, color = "#444B54") +
  geom_hline(yintercept = mean_temp, color = "#2980B9", size = 1.5, alpha = 0.2, linetype = 2) +
  geom_errorbar(aes(ymin = Min, ymax = Max), width = .5, color = "#444B54", size = 5) +
  ylab("\nTemperatur (°C)") +
  xlab("\nMonat") +
  geom_text(aes(y=Min), label = min, vjust = 1.9) +
  geom_text(aes(y=Max), label = max, vjust = -1.1) +
  ylim(-8, 30) +
  ggtitle("Monatliche Durchschnittstemperaturen", subtitle = "für Bern 1981 – 2010") +
  theme(panel.background = element_blank(),
        # panel.grid.major = element_line(color = "#F0F1F5", size = 0.2),
        panel.grid.minor = element_blank()
        )
```

### Exportieren

```{r export_webscraping, fig.align='center'}
panda(tidy_df[, .(Monat, Max, Min)], style = "rmarkdown")
```
stargazer(tidy_table, type = "html", summary = FALSE)






